### ISSUE TITLE
Unable to compile: ERROR in ./node_modules/icecat/lib/OpenCatalog/service.js

### ISSUE THREAD

**Issue by tommichaelford** [GreenCore/icecat#18]
Module not found: Error: Can't resolve 'https' in 'C:\Documents\basicapp\node_modules\icecat\lib\OpenCatalog'

Would this be an issue on my end? Https nodemodule is installed and nothing else has issues finding this. Is there anything you can advise?

Cheers, Tom.

**Comment by tommichaelford** [comment]
Would this be an issue on my end? Https nodemodule is installed and nothing else has issues finding this. Is there anything you can advise? 

Cheers, Tom.

**Comment by alexdrans** [comment]
https is a core module, so you shouldn't need to install it, and it doesn't need to be in your local node_modules.

All I can suggest is `rm -rf node_modules && npm i`. Show me your package.json if that doesn't work.

**Comment by tommichaelford** [comment]
Sorry it was an issue on my end not understanding what I was doing, apologies.
