### ISSUE TITLE
getImages throws error

### ISSUE THREAD

**Issue by jimmywarting** [GreenCore/icecat#33]
I found a product that don't have any image so this line fails

https://github.com/GreenCore/icecat/blob/5be178ffc63c0b60bbd5e0af296624f81dd53017/lib/OpenCatalog/product.js#L193

Cannot read property 'map' of undefined

```xml
  <ProductGallery/>
```

**Comment by GreenCore** [comment]
@jimmywarting thanks for reporting! 
The fix for your issue report has been included in the V1.4.4 update.
https://www.npmjs.com/package/icecat

**Comment by jimmywarting** [comment]
Thanks for a quick fix
