### ISSUE TITLE
If ProductGallery is undefined, getImages() crash

### ISSUE THREAD

**Issue by erocheleau** [GreenCore/icecat#37]
`Cannot read property 'length' of undefined
    at icecat.getImages (icecat/lib/OpenCatalog/product.js:193:40)`

`if (!this.productData.ProductGallery.length || !this.productData.ProductGallery[0].ProductPicture.length)` 
isn't safe if ProductGallery is undefined.

**Comment by GreenCore** [comment]
Thank you @erocheleau for your improvement! This has now been implemented and also published on https://www.npmjs.com/package/icecat
